### PR TITLE
Make initial fetch balance optional for feed

### PR DESCRIPTION
**Pull request by sandroboehme**
At least at Binance and probably on other exchanges too fetching ohlcv data doesn't need authentication while obviously fetching the balance of ones account does need authentication.
Usually the CCXTStore fetches the balance when it is initialized which is perfect during live trading operation.
But the store is also initialized when the CCXTFeed is created and used during unit testing and backtesting. For this case it is beneficial to turn off the initial fetching of the balance as it is not really needed and it avoids needing to have api keys.

This makes it possible for users that don't have a Binance api key to run backtesting and unit tests with real ohlcv data.

### CODE REVIEW

**Comment by Dave-Vallance** [comment]
@sandroboehme Thanks for the additional contributions.... I am a bit hammered with work lately and will try and get around to this when I can!

**Comment by Dave-Vallance** [comment]
@sandroboehme 

Like the idea to allow forward testing. 

After review I am wondering whether we should put "broker" or "account" specific parameters within the ccxtfeed.py

I see that in the test you are calling `CCXTFeed()` directly. The usual process is to call the store, then `store.getbroker()` and finally `store.getdata()`. 

I am thinking it would be nice to develop this in a way that we can just call the store and then `store.getdata()` only. I.e Omit `getbroker()` and then we run with the backtrader broker for paper trading. 

Also, I hope this would avoid us having to put `initially_fetch_balance` inside ccxtfeed.py.  

What do you think?

**Comment by sandroboehme** [comment]
@Dave-Vallance 
To be honest I don't know what would align best with Backtrader. But it sounds like it would be a better separation between Backtrader and the CCXT implementations.

**Comment by Dave-Vallance** [comment]
@sandroboehme 
 
Sorry - I am not ignoring this one. I just have not had a chance to think about how to implement it yet. Next week is looking to be a really busy week too :( 

Will try and get around to it as soon as possible.

**Comment by sandroboehme** [comment]
@Dave-Vallance 
Don't worry. I have it working in my branch which is good enough for now.

**Comment by Dave-Vallance** [comment]
@sandroboehme 

I am thinking to try and get this working so we continue to use the store as the primary point of interaction to keep things consistent. 

So we might just need to accept the `ccxtstore.py` change and reject the `ccxtfeed.py` change. This should be possible without any major changes to your code. (If I am thinking about this correctly)

If we do that, the procedure would be something like:

1) Call the store without your API keys in the config and set `initially_fetch_balance` to `False`
2) Use `store.getdata()` to load the feeds.

A bonus would be to add a feature to detect that we didn't include the API keys in the config file and then prevent the `store.getbroker()` from being called (with a nice error message)

Can you try to load it that way and see if it works? If so, we can avoid having the `initially_fetch_balance` parameter in `ccxtfeed.py`. You should be able to do this with the current code in your branch. 

It might just be my OCD - But I prefer not have anything account related in `ccxtfeed.py` as that should only be for the feed. :)

**Comment by sandroboehme** [comment]
@Dave-Vallance 
That's a very good idea! I've simply changed the initial fetching of the balance to depend on the api-keys to be defined.

> Use store.getdata() to load the feeds.
Sorry, but I don't really know for sure where to change that.
I've also added a `backtesting.py` sample but it calls `next()` only three times and it isn't really clear to me why that is the case. It might have something to do with #8 .

**Comment by Dave-Vallance** [comment]
@sandroboehme 

> sorry, but I don't really know for sure where to change that.

Sorry - I wasn't clear. I mean that we can probably get data without using CCXTFeed() directly by following those steps.

**Comment by Dave-Vallance** [comment]
@sandroboehme 

Great work on this one! About to merge now. 

FYI - Here is a simple gist for using the store method to pull data rather than imprting CCXTFeed directly. You don't need to follow this method because both work. It is just an FYI. 

https://gist.github.com/Dave-Vallance/f4f8bf0885088ebe8e3175f3521dbff5

**Comment by pfederra** [comment]
Hi @sandroboehme and @Dave-Vallance,

Has this issue been resolved and integrated in the main branch? Because I still get the exact same issue when running the CCXTFeed without api key.

When I run the test_optional_fetch_balance.py this works but I suppose this is just temp fix.
Thanks

**Pull request merged**
